DATA_DIR = "/Users/kuatul/Desktop/IISC-ML&AI/Capstone_Project/"
train_path = "/Users/kuatul/Desktop/IISC-ML&AI/Capstone_Project/Final_Training/Images"
test_path = "/Users/kuatul/Desktop/IISC-ML&AI/Capstone_Project/Final_Test/Images"
ARTIFACTS_DIR = "/Users/kuatul/Desktop/IISC-ML&AI/Capstone_Project/artifacts"
MODEL_SAVE_PATH = "traffic_sign_model.h5"
INPUT_SHAPE = (50, 50, 3)
NUM_CLASSES = 43
TEST_SIZE = 0.2
EPOCHS = 10
BATCH_SIZE = 32
LABEL_FILE = "/Users/kuatul/Desktop/IISC-ML&AI/Capstone_Project/Final_Training/labels.csv"